### ISSUE TITLE
Kafka 要点

### ISSUE THREAD

**Issue by yifanzheng** [yifanzheng/cs-notes#30]
## Kafka

Kafka 是消息引擎系統，也是分布式实时流式处理平台。而流式处理框架的优势在于更容易实现端到端的正确性，轻量型，嵌入式流式计算的定位；

### 环境准备

在开始前，首先准备好自己的 docker 环境，可以安装 [Docker Desktop](https://www.docker.com/products/docker-desktop).

为了更方便的搭建学习环境，推荐使用 confluent 公司社区版 docker 镜像。

对于 confluent 版本和 apache 版本对照表见：[Confluent Platform and Apache Kafka Compatibility](https://docs.confluent.io/platform/current/installation/versions-interoperability.html)

1. 新建文件 `docker-compose.yml`，并写入如下内容：
```yml
---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
```
2. 使用 `docker-compose up -d` 启动；
3. `docker-compose down` 可以关闭创建好的集群;

参考：[Apache Kafka® Quick Start](https://developer.confluent.io/quickstart/kafka-docker/)

### 核心要点

**实践**

- [如何保证高可用](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-883021460)
- [如何保证消息消费的幂等性（即不重复消费）](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-883021991)
- [如何保证消息不弄丢](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-883022470)
- [Kafka Producer acks 参数介绍](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-883409248)
- [顺序消息实现](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-883461725)
- [Kafka 为何如此快？](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-884245498)
- [可能导致数据丢失的几种情形](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1066497856)

**原理**
- [Kafka 集群参数配置](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1201151456)
- [Kafka 生产者分区策略](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1201207063)
- [Kafka Rebalance ](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1205318305)
- [Consumer 位移提交](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1206218856)
- [生产者与消费者的 TCP 管理](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1207231089)
- [Kafka 请求是怎么被处理的](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1207881764)
- [Kafka 高水位机制和 Leader Epoch](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1208045293)
- [Kafka 调优](https://github.com/yifanzheng/java-notes/issues/30#issuecomment-1208257225)
