### ISSUE TITLE
ETCD 要点

### ISSUE THREAD

**Issue by yifanzheng** [yifanzheng/cs-notes#99]
## ETCD

ETCD 是一个强大的一致性的分布式键值存储，它提供了一种可靠的方式来存储需要由分布式系统或机器群访问的数据。它优雅地处理网络分区期间的领导者选举，并且可以容忍机器故障，即使在领导者节点中也是如此。ETCD 常用于分布式配置、分布式锁、分布式服务协调者以及分布式注册。

## Raft 共识算法

在理解 Raft 算法原理之前，我们先理解什么是共识？

共识是容错分布式系统中的一个基本问题。共识涉及多个服务器就值达成一致。一旦它们就某个值做出决定，该决定就是最终决定。当大多数服务器可用时，典型的共识算法会取得进展；例如，一个由 5 台服务器组成的集群即使有 2 台服务器发生故障，也可以继续运行。如果更多服务器出现故障，它们将停止前进（但永远不会返回不正确的结果）。

Raft 将一致性问题分解成了三个相对独立的子问题：
- **领导者选举**：当现存的领导人发生故障的时候，一个新的领导人需要被选举出来。
- **日志复制**：领导人必须从客户端接收日志条目（log entries）然后复制到集群中的其他节点，并强制要求其他节点的日志和自己保持一致。
- **安全性**：如果有任何的服务器节点已经应用了一个确定的日志条目到它的状态机中，那么其他服务器节点不能在同一个日志索引位置应用一个不同的指令。

### 节点状态

一个节点可以处于以下三种状态之一：

- Follower：跟随者，同步从 Leader 收到的日志；
- Candidate：候选者，可以发起 Leader 选举；
- Leader：领导者，集群唯一，拥有同步日志的特权，需要定时广播心跳给 Follower 节点，以维持领导者身份;

我们所有的节点都以跟随者状态开始。

### 领导者选举

当服务器程序启动时，它们都是跟随者状态，如果跟随者没有收到领导者的来信，那么他们可以成为候选人。然后，候选人从其他节点请求投票，节点将以他们的投票进行回复。如果候选人从多数节点中获得选票，它将成为领导者。这个过程称为**领导者选举(Leader Election)**。

Raft 使用一种**心跳机制来触发领导人选举**。一个服务器节点继续保持着跟随者状态只要它从领导人或者候选人处接收到有效的心跳包。领导人周期性的向所有跟随者发送心跳包来维持自己的权威。如果一个跟随者在一段时间里没有接收到任何消息，也就是**选举超时**，那么它就会认为系统中没有可用的领导人，并且发起选举以选出新的领导人。

**选举过程**
- 选举超时后，Follower 先要增加自己的当前任期号并且转换到 Candidate 状态，并开始一个新的选举任期；
- Candidate 节点会为自己投票，并将向其他节点发送**请求投票**(Request Vote)消息以争取选票，Follower 会将自己的任期号返回给候选人；
  - 如果 Candidate 的数据和自己一样、任期号比自己的大且没有投票给其他 Candidate，就会投票给此 Candidate；
  - 如果恰好 Follower 也心跳超时超过竞选时间了，它也发起了选举，并投票给了自己，那么它将拒绝投票给 Candidate，这时谁也无法获取集群多数派支持，只能等待竞选超时，开启新一轮选举。Raft 为了优化选票被瓜分导致选举失败的问题，引入了随机数，每个节点等待发起选举的时间点不一致，优雅的解决了潜在的竞选活锁。
- 如果其它节点在此选举任期内还没有投票，那么它将把票投给 Candidate，然后将重置选举超时；
- 一旦 Candidate 获得多数（过半）选票，那么它将成为领导者；然后它会向其他的节点发送**心跳消息**来建立自己的权威并且阻止发起新的选举。
- 这些消息以**心跳超时**指定的时间间隔发送，Follower 响应每个心跳消息，此选举任期将持续到 Follower 停止接收心跳并成为 Candidate 为止。

要获得多数票，可以确保每个任期只能选出一位领导者。如果两个节点同时成为候选节点，则可能会发生分裂投票。比如每个节点都先到达一个跟随者节点，现在，每个候选人都有 2 票，并且在这个任期中将无法获得更多选票（过半的票数）。节点将等待新的选举，然后再试一次。

**心跳间隔时间**：Leader 向 Follower 发送心跳信息的时间，默认间隔 100ms；
**竞选超时时间**：Leader 异常后发起重新选举的时间，默认 1000ms;
**选举超时**：Follower 成为 Candidate 之前所等待的时间，此值被随机分配在 150ms - 300ms 之间；目的是减少选票被瓜分导致选举失败的问题（解决潜在的竞选活锁问题）。

### 日志复制

- 系统的所有更改都只能通过 Leader 进行；
- 更改条目时，首先追加到 Leader 日志中，但是处于未提交的状态；
- 然后 Leader 将条目复制到所有的 Follower 节点，并等待直到大多数（过半）节点都写入了该条目；
- Leader 确认大多数（过半）节点写入成功后，会提交该条目，并随后通知各个 Follower 提交该条目；
- Follower 更新完成后，系统便已达成共识；

此过程就是日志复制(Log Replication)。

### 安全性

- **选举限制**：当一个节点收到选举投票的时候，需要检查候选人的当前任期号，如果任期号小于自己的任期号，则拒绝投票；如果任期号相同，但是日志条目比自己的短，也拒绝为其投票，**即在选主逻辑中，对能够成为主的节点加以限制，确保选出的节点已定包含了集群已经提交的所有日志**。
- **日志复制规则**：
  - Leader 完全特性：如果某个日志条目在某个任期号内已经被提交了，那么这个日志条目必然出现在更大任期号的所有 Leader 中；（保证不丢数据）
  - 只附加原则：Leader 只能追加日志条目，不能删除已经持久化的日志条目；
  - 日志匹配特性：Leader 在发送追加日志消息时，会把新的日志条目紧接着之前的条目的索引位置和任期号包含在里面；Follower 节点会检查相同索引位置的任期号是否与 Leader 的一致，一致才进行追加。（保证一致性）

### 如何解决网络分区的问题

- 网络分区后，节点数量较少的那部分分区无法完成新任期的 Leader 选举，并且无法提交条目；
- 网络分区后，节点数量较多的那部分分区可正常的选举、提交条目；
- 网络正常后，较少节点的那部分节点因为没有新的数据写入，所以只需要回滚之前未提交的数据，并同步数量较多的那部分节点中的数据即可；

### 集群安装

创建 `docker-compose.yml` 文件，使用 `docker compose up` 启动。
```yaml
version: "3.6"
services:

  node1:
    image: quay.io/coreos/etcd:v3.4.0
    volumes:
      - node1-data:/etcd-data
    expose:
      - 2379
      - 2380
    networks:
      cluster_net:
        ipv4_address: 172.16.238.100
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - node1
      - --initial-advertise-peer-urls
      - http://172.16.238.100:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.16.238.100:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - docker-etcd

  node2:
    image: quay.io/coreos/etcd:v3.4.0
    volumes:
      - node2-data:/etcd-data
    networks:
      cluster_net:
        ipv4_address: 172.16.238.101
    environment:
      - ETCDCTL_API=3
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - node2
      - --initial-advertise-peer-urls
      - http://172.16.238.101:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.16.238.101:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - docker-etcd

  node3:
    image: quay.io/coreos/etcd:v3.4.0
    volumes:
      - node3-data:/etcd-data
    networks:
      cluster_net:
        ipv4_address: 172.16.238.102
    environment:
      - ETCDCTL_API=3
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - node3
      - --initial-advertise-peer-urls
      - http://172.16.238.102:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://172.16.238.102:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --initial-cluster
      - node1=http://172.16.238.100:2380,node2=http://172.16.238.101:2380,node3=http://172.16.238.102:2380
      - --initial-cluster-state
      - new
      - --initial-cluster-token
      - docker-etcd

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
```

## 参考

中文[翻译地址](https://github.com/maemual/raft-zh_cn/blob/master/raft-zh_cn.md)

## Tips

- [ETCD 存储](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1113904363)
- [ETCD 支持的机制](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1114129937)
- [ETCD 内存使用](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1132889446)
- [ETCD 调优](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1154775716)
- [ETCD DB 大小影响面](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1175163718)
- [思考](https://github.com/yifanzheng/java-notes/issues/99#issuecomment-1179724967)
